### ISSUE TITLE
Add code

### ISSUE THREAD

**Issue by impredicative** [EmillieT/Pycee#1]
https://arxiv.org/pdf/1906.11456v1.pdf says:

> PYCEE is available as an open-source project on GitHub. 6

> 6 https://github.com/EmillieT/Pyce

Did I miss something here? Where is the code?

**Comment by EmillieT** [comment]
Apologies, you should now be able to see the code

**Comment by impredicative** [comment]
OK. Please mention and add a link to the ArXiv paper in the readme.
